---
  - name: Cleanup CSS service
    otc_css:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      validate_certs: "yes"
      name: "{{ net.vpc.name }}-css"

  # retry deletion of security group until
  # cluster really disappered from the network
  - name: Cleanup security group
    os_security_group:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      validate_certs: "yes"
      name: "{{ net.vpc.name }}-css-sg"
    register: delete_state
    retries: 20
    delay:   15
    until: delete_state is not failed