---
  - name: "Cleanup backend subnet {{ net.subnets.backend.name }}"
    otc_subnet:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      name: "{{ net.subnets.backend.name }}" 

  - name: "Cleanup worker subnet {{ net.subnets.worker.name }}"
    otc_subnet:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      name: "{{ net.subnets.worker.name }}" 

  - name: "Cleanup access subnet {{ net.subnets.access.name }}"
    otc_subnet:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      name: "{{ net.subnets.access.name }}"

  - name: Cleanup VPC network
    otc_vpc:
      state: "absent"
      auth_type: password
      auth:
        "{{ otc_os_auth }}"
      cacert: "{{ otc_cert_file }}"
      name: "{{ net.vpc.name }}"
