#!/bin/bash

kubectl apply -f kube-dashboard-cluster-role.yaml
# see https://github.com/kubernetes/dashboard/releases for current dashboard version and compatibility
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc1/aio/deploy/recommended.yaml

# this generates a suitable bearer token for the previously established service account
echo
echo  "*** Generate an initial bearer token"
kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep kubernetes-dashboard | awk '{print $1}')

echo
echo "*** Next steps:"
echo "Establish an SSH tunnel to your local machine, default port 8001, then open"
echo "kubectl proxy & on your remote ssh machine you are logged in"
echo "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/"
