#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

replace_or_add_line() {
   sudo -- bash -c "grep -q -E \"$1$2\" $4 || sed -i \"s/$1$/& $3/\" $4"
}

append_if_missing() {
   grep -q \"$1\"" $3 || echo $2 >> $3
}

###
# Install Docker CE
# It is required to send docker command by commandline tool and
# to pack images using Dockerfile
sudo yum-config-manager \
   --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum -y makecache fast
sudo yum -y install docker-ce

sudo groupadd docker
sudo usermod -aG docker $USER

###
# FIXME Enable repo access (disable cert check)
# disable strict certificate checking 
# (certs do not contain IPs/servernames/subjectaltids)
replace_or_add_line "ExecStart=.*" "--insecure-registry[ \t]*[\\\"\\']?100.125.7.25:20202[\\\"\\']?" \
   "--insecure-registry \"100.125.7.25:20202\"" "/usr/lib/systemd/system/docker.service"
replace_or_add_line "ExecStart=.*" "--insecure-registry[ \t]*[\\\"\\']?80.158.24.86[\\\"\\']?" \
   "--insecure-registry \"80.158.24.86\"" "/usr/lib/systemd/system/docker.service"


# finally, start docker daemon
sudo systemctl daemon-reload
sudo systemctl enable docker
sudo systemctl start docker

###
# Log in to repo
# 
$DIR/auth_registry $1

###
# Some useful shortcuts for Docker
#
#append_if_missing() "docker_clean_images" "\
## some useful Docker aliases\
#alias docker_clean_images='docker rmi \$(docker images -a --filter=dangling=true -q)'\
#alias docker_clean_ps='docker rm \$(docker ps --filter=status=exited --filter=status=created -q)'" \
#~/.bashrc
