#!/bin/bash
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Secret
metadata:
  name: $(echo $1)
  namespace: $(echo ${2:-default})
data:
  .dockercfg: `cat ~/.docker/config.json |jq --compact-output .auths|base64 -w 0`
type: kubernetes.io/dockercfg
EOF
