apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-09-13T10:57:24Z
  labels:
    app: elk-objectstore-app
  name: elasticsearch-service
  namespace: default
spec:
  selector:
    app: elk-objectstore-app
  sessionAffinity: None
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: elk-objectstore-app
  name: elasticsearch-service
subsets:
  - addresses:
      - ip: 10.147.34.205
    ports:
      - port: 9200
