apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: elk-objectstore-app
    version: "1.19.1113"
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk-objectstore-app
      version: "1.19.1113"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elk-objectstore-app
        version: "1.19.1113"
        # version: latest
      name: elk-objectstore-tmpl
    spec:
      containers:
      - image: 100.125.7.25:20202/bmw1/logstash:1.5
        imagePullPolicy: Always
        name: elk-objectstore-elasticsearch
        resources: {}
        stdin: true
        tty: true
        securityContext:
          privileged: false
        env:
        - name: ELASTICSEARCH_SERVICE_HOST
          value: "10.147.34.205"
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "9200"
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: pullsecret-bmw1
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
